### PR TITLE
Fix text and screenshots on welcome page

### PR DESCRIPTION
**Pull request by rabia-pullflow**
Fixed typos and added screenshots and gifs.

### CODE REVIEW

**Comment by zakmandhro** [comment]
@rabia-pullflow @srzainab I fixed more issue with the welcome text.

**Comment by zakmandhro** [comment]
Fixes #35

**Comment by srzainab** [comment]
1. In assets/pr-chat.gif - can we focus on the PR thread on the slack side? Zoom in further? 
2. On assets/pr-dashboard.png - can we show atleast one PR where the user is requested review? 
3. image

**Review by srzainab — CHANGES_REQUESTED** [review]

**Comment by rabia-pullflow** [comment]
When I zoomed in on the side it kept disappearing completely, a slack bug maybe

**Comment by srzainab** [comment]
You can use this button to make it a separate window and then make it as big as you want
[image.png](https://files.slack.com/files-pri/T01ERL1BUMR-F068SEL7561/image.png)

**Comment by rabia-pullflow** [comment]
For the iconography image, we need to add this visual guide to the right for better visibility

**Review by srzainab — CHANGES_REQUESTED** [review]
Requires more work

**Review by srzainab — APPROVED** [review]

**Pull request merged**
